/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

declare const window: any;

const awsmobile = {
    "aws_project_region": window.ENV.AWS_PROJECT_REGION || '', // "us-east-1",
    "aws_cognito_identity_pool_id": window.ENV.AWS_COGNITO_IDENTITY_POOL_ID || '', // "us-east-1:64e2db0e-ac01-4b72-96c4-eea02623f02b",
    "aws_cognito_region": window.ENV.AWS_COGNITO_REGION || '', // "us-east-1",
    "aws_user_pools_id": window.ENV.AWS_USER_POOLS_ID || '', // "us-east-1_8c1pujn9g",
    "aws_user_pools_web_client_id": window.ENV.AWS_USER_POOLS_WEB_CLIENT_ID || '', // "39be0fqctitbmhp1mba6et2ofu",
    "oauth": {}
};

export default awsmobile;
