/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:64e2db0e-ac01-4b72-96c4-eea02623f02b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8c1pujn9g",
    "aws_user_pools_web_client_id": "39be0fqctitbmhp1mba6et2ofu",
    "oauth": {}
};


export default awsmobile;
